[package]
name = "aoi"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
anyhow = "1.0"
clap = "3.0.0-beta.1"
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "llvm10-0" }
rustyline = "6.1"
unicode-xid = "0.2"
